name = "mefa-platform"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "mefa-db"
database_id = "765ae9e2-7142-4e44-b4ec-5680637fe49d"

# Environment variables
[vars]
NODE_ENV = "production"